name: "Trello Traceability GitHub Action"
author: "Neo4j"
description: "Ensures git commit messages contain a Trello short link"
branding:
  icon: 'award'
  color: 'green'
inputs:
  global_verification_strategy:
    required: false
    default: "commits"
    description: "One of comments, commits, title, disabled."
  trello_api_key:
    required: true
    description: "API key for Trello. Use GitHub secrets. Don't use plaintext."
  trello_api_token:
    required: true
    description: "API token for Trello. Use GitHub secrets. Don't use plaintext."
  github_api_token:
    required: true
    description: "API token for GitHub. Use GitHub secrets. Don't use plaintext."
runs:
  using: "node16"
  main: "dist/index.js"
