name: traceability

permissions:
  checks: write

on:
  issue_comment: # // daniel document
    types:
      - created
      - edited
      - deleted

  pull_request:
    branches:
      - dev
    types:
      - labeled # // daniel document
      - unlabeled # // daniel document
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  pr-update:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request
    steps:
      - name: "Get check suites for a git commit"
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/neo4j/github-action-traceability/commits/040187ff3e4364e58c3535159868a60888231ef1/check-suites
      - name: "Get check suite"
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/neo4j/github-action-traceability/check-suites/11399901024
      - name: "Re-request check suite"
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/neo4j/github-action-traceability/check-suites/11399901024/rerequest
      - name: "Get check runs for a git commit"
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/neo4j/github-action-traceability/commits/040187ff3e4364e58c3535159868a60888231ef1/check-runs
      - name: "Re-request a check-run"
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/neo4j/github-action-traceability/check-runs/11819564903/rerequest
      - name: "Create a check-run"
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/neo4j/github-action-traceability/check-runs \
              -d '{"name":"pr-update","head_sha":"040187ff3e4364e58c3535159868a60888231ef1","status":"in_progress","started_at":"2018-05-04T01:14:52Z","output":{"title":"Mighty Readme report2","summary":"","text":""}}'

# // daniel works but doesn't update an existing pr check...
#      - name: Get PR branch
#        uses: xt0rted/pull-request-comment-branch@v1
#        id: comment-branch
#
#      - name: Set PR Status to pending
#        uses: teamniteo/pull_request_status_action@v1.0.0
#        with:
#          pr_number: 12
#          repository: neo4j/github-action-traceability
#          state: pending
#          context: traceability / pr-update (pull_request)
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# // daniel works but doesn't update an existing pr check...
#      - name: Set latest commit status as pending
#        uses: myrotvorets/set-commit-status-action@master
#        with:
#          sha: ${{ steps.comment-branch.outputs.head_sha }}
#          token: ${{ secrets.GITHUB_TOKEN }}
#          status: pending

#      - uses: neo4j/github-action-traceability@v2
#        with:
#          trello_api_key: ${{ secrets.TRELLO_API_KEY }}
#          trello_api_token: ${{ secrets.TRELLO_API_TOKEN }}
#          github_api_token: ${{ secrets.GITHUB_TOKEN }}
