name: traceability-comments-trigger

on:
  issue_comment:
    types:
      - created
      - edited
      - deleted



jobs:
  traceability-comments-trigger:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request
    steps:
#      - uses: actions/github-script@v3
#        id: get-pr
#        with:
#          script: |
#            const request = {
#              owner: context.repo.owner,
#              repo: context.repo.repo,
#              pull_number: context.issue.number
#            }
#            core.info(`Getting PR #${request.pull_number} from ${request.owner}/${request.repo}`)
#            try {
#              const result = await github.pulls.get(request)
#              return result.data
#            } catch (err) {
#              core.setFailed(`Request failed with error ${err}`)
#          }
      - name: "Get Pull Request"
        id: get-pr
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/pulls/${{ github.event.issue.number }}"
      - name: "Get Commit"
        id: get-commit
#        run: gh pr view ${{ github.event.issue.number }} --repo $GITHUB_REPOSITORY --json headRefOid --jq ".headRefOid"
        run: gh pr view ${{ github.event.issue.number }} --repo $GITHUB_REPOSITORY --json headRefOid
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Show result"
        run: |
          echo ${{ fromJSON(steps.get-commit.outputs).headRefOid }}
          echo ${{ fromJSON(steps.get-commit.outputs.result).headRefOid }}
      - name: "Get check suites for a git commit"
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/neo4j/github-action-traceability/commits/040187ff3e4364e58c3535159868a60888231ef1/check-suites"
      - name: "Get check suite"
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/neo4j/github-action-traceability/check-suites/11399901024
      - name: "Re-request check suite"
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/neo4j/github-action-traceability/check-suites/11399901024/rerequest
