name: traceability-comments-trigger

on:
  issue_comment:
    types:
      - created
      - edited
      - deleted



jobs:
  traceability-comments-trigger:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request
    steps:
      - name: "Get Commit"
        id: get-commit
        run: |
          SHA=$( gh pr view ${{ github.event.issue.number }} \
            --repo $GITHUB_REPOSITORY \
            --json headRefOid \
            --jq .headRefOid 
          )
          echo "sha=$SHA" > $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Get Check Suites For Commit"
        run: |
          SUITES=$( curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/commits/${{ steps.get-commit.outputs.sha }}/check-suites"
          )
          echo $SUITES
      - name: "Get check suite"
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/neo4j/$GITHUB_REPOSITORY/check-suites/11399901024
      - name: "Re-request check suite"
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/neo4j/github-action-traceability/check-suites/11399901024/rerequest
