name: traceability

on:
  issue_comment: # // daniel document
    types:
      - created
      - edited
      - deleted

  pull_request:
    branches:
      - dev
    types:
      - labeled # // daniel document
      - unlabeled # // daniel document
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  pr-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        if: ${{ github.event.issue.pull_request }}
        run: |
          gh pr checkout ${{ github.event.issue.number }}
      - uses: neo4j/github-action-traceability@v2
        with:
          trello_api_key: ${{ secrets.TRELLO_API_KEY }}
          trello_api_token: ${{ secrets.TRELLO_API_TOKEN }}
          github_api_token: ${{ secrets.GITHUB_TOKEN }}
