name: traceability-comments-trigger

on:
  issue_comment:
    types:
      - created
      - edited
      - deleted

jobs:
  traceability-comments-trigger:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request
    steps:
      #      - uses: actions/github-script@v3
        #        id: get-commit
        #        with:
        #          script: |
        #            const request = {
        #              owner: context.repo.owner,
        #              repo: context.repo.repo,
        #              pull_number: context.issue.number
        #            }
        #            core.info(`Getting PR #${request.pull_number} from ${request.owner}/${request.repo}`)
        #            try {
        #              const result = await github.pulls.get(request)
        #              core.info(JSON.stringify({result}, null, 2))
        #              return result.data
        #            } catch (err) {
        #              core.setFailed(`Request failed with error ${err}`)
      #            }
      - name: "Get Commit"
        id: get-commit
        run: |
          SHA=$( gh pr view ${{ github.event.issue.number }} \
            --repo $GITHUB_REPOSITORY \
            --json headRefOid \
            --jq .headRefOid
          )
          echo "sha=$SHA" > $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Get Runs For Commit"
        id: get-runs
        run: |
          RUNS=$( curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/commits/${{ steps.get-commit.outputs.sha }}/check-runs?check_name=traceability-comments"
          )
          echo "runs=$RUNS" > $GITHUB_OUTPUT
      - name: "Get Suite"
        id: get-run
        run: |
          echo ${{ steps.get-runs.outputs.runs }}
          echo "run=${{ fromJSON(steps.get-runs.outputs.runs).check_runs[0].check_suite.id }}"
          echo "run=${{ fromJSON(steps.get-runs.outputs.runs).check_runs[0].check_suite.id }}" > $GITHUB_OUTPUT
      - name: "Re-request check suite"
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/check-suites/11407763024/rerequest"
