name: traceability-comments-trigger

on:
  issue_comment:
    types:
      - created
      - edited
      - deleted

jobs:
  traceability-comments-trigger:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request
    steps:
      - name: "Get Pull Request"
        id: get-pr
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/neo4j/github-action-traceability/pulls/${{ github.event.issue.number }}"
      - name: "Get Commit"
        id: get-commit
        run: |
          gh pr view ${{ github.event.issue.number }}
      - name: "Get check suites for a git commit"
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/neo4j/github-action-traceability/commits/040187ff3e4364e58c3535159868a60888231ef1/check-suites"
      - name: "Get check suite"
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/neo4j/github-action-traceability/check-suites/11399901024
      - name: "Re-request check suite"
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/neo4j/github-action-traceability/check-suites/11399901024/rerequest
